
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Note: Storage, Offload and Offload2 can all be enabled or disabled independently.
# However, at least one of these three outputs must be enabled.

apiVersion: analytics.apiconnect.ibm.com/v1beta1
kind: AnalyticsCluster
metadata:
  name: analytics
spec:
  version: $APP_PRODUCT_VERSION
  license:
    accept: true
    use: production
    license: ''
  profile: $PROFILE
  imagePullSecrets:
  - $SECRET_NAME
  imageRegistry: $DOCKER_REGISTRY
  microServiceSecurity: certManager
  certManagerIssuer:
    name: selfsigning-issuer
    kind: Issuer
  ingestion:
    endpoint:
      annotations:
        cert-manager.io/issuer: ingress-issuer
      hosts: 
      - name: ai.$STACK_HOST
        secretName: analytics-ai-endpoint
    clientSubjectDN: CN=analytics-ingestion-client,O=cert-manager
  storage:
    enabled: true
    type: $STORAGE_TYPE
    shared:
      volumeClaimTemplate:
        storageClassName: $STORAGE_CLASS
        volumeSize: $DATA_VOLUME_SIZE
  external:
    offload:
      enabled: true
      output: |
        kafka {
          topic_id => "$KAFKA_TOPIC"
          bootstrap_servers => "$EXTERNAL_KAFKA_HOST"
          codec => "json"
          id => "offload_kafka"
        }
      secretName: ''
      passwordSecretName: ''
    offload2:
      enabled: true
      filter: |
        mutate {
          remove_field => ["query_string"]
        }
      output: |
        if  [log_policy] == "payload" {
          http {
            url => "$EXTERNAL_HOST2_URL"
            http_method => "post"
            codec => "json"
            content_type => "application/json"
            id => "offload2_http"
          }
        }
      secretName: ''
      passwordSecretName: ''
