
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: analytics.apiconnect.ibm.com/v1beta1
kind: AnalyticsCluster
metadata:
  name: analytics
spec:
  version: 10.0.9.0
  license:
    accept: true
    use: production
    license: L-WPTV-3V8RK2
  profile: n1xc2.m16
  imagePullSecrets:
  - apic-registry-secret
  imageRegistry: hcr.161.156.84.163.nip.io/apic
  microServiceSecurity: certManager
  certManagerIssuer:
    name: selfsigning-issuer
    kind: Issuer
  ingestion:
    endpoint:
      #ingressClassName: $INGRESS_CLASS
      annotations:
        cert-manager.io/issuer: ingress-issuer
      hosts: 
      - name: ai.192.168.49.2.nip.io
        secretName: analytics-ai-endpoint
    clientSubjectDN: CN=analytics-ingestion-client,O=cert-manager
  mtlsValidateClient: true
  storage:
    type: shared
    shared:
      volumeClaimTemplate:
        storageClassName: standard
        volumeSize: 50Gi
